export const GET_ALL_CLOTHES_BRAND_REQUEST = 'GET_ALL_CLOTHES_BRAND_REQUEST'
export const GET_ALL_CLOTHES_BRAND_SUCCESS = 'GET_ALL_CLOTHES_BRAND_SUCCESS'
export const GET_ALL_CLOTHES_BRAND_FAIL = 'GET_ALL_CLOTHES_BRAND_FAIL'

export const GET_ALL_SHELTER_BRAND_REQUEST = 'GET_ALL_SHELTER_BRAND_REQUEST'
export const GET_ALL_SHELTER_BRAND_SUCCESS = 'GET_ALL_SHELTER_BRAND_SUCCESS'
export const GET_ALL_SHELTER_BRAND_FAIL = 'GET_ALL_SHELTER_BRAND_FAIL'

export const GET_ALL_MEAL_BRAND_REQUEST = 'GET_ALL_MEAL_BRAND_REQUEST'
export const GET_ALL_MEAL_BRAND_SUCCESS = 'GET_ALL_MEAL_BRAND_SUCCESS'
export const GET_ALL_MEAL_BRAND_FAIL = 'GET_ALL_MEAL_BRAND_FAIL'

export const GET_SINGLE_BRAND_REQUEST = 'GET_SINGLE_BRAND_REQUEST'
export const GET_SINGLE_BRAND_SUCCESS = 'GET_SINGLE_BRAND_SUCCESS'
export const GET_SINGLE_BRAND_FAIL = 'GET_SINGLE_BRAND_FAIL'


export const GET_ALL_MEAL_PRODUCT_REQUEST = 'GET_ALL_MEAL_PRODUCT_REQUEST'
export const GET_ALL_MEAL_PRODUCT_SUCCESS = 'GET_ALL_MEAL_PRODUCT_SUCCESS'
export const GET_ALL_MEAL_PRODUCT_FAIL = 'GET_ALL_MEAL_PRODUCT_FAIL'

export const GET_ALL_CLOTHES_PRODUCT_REQUEST = 'GET_ALL_CLOTHES_PRODUCT_REQUEST'
export const GET_ALL_CLOTHES_PRODUCT_SUCCESS = 'GET_ALL_CLOTHES_PRODUCT_SUCCESS'
export const GET_ALL_CLOTHES_PRODUCT_FAIL = 'GET_ALL_CLOTHES_PRODUCT_FAIL'


export const GET_ALL_SHELTER_PRODUCT_REQUEST = 'GET_ALL_SHELTER_PRODUCT_REQUEST'
export const GET_ALL_SHELTER_PRODUCT_SUCCESS = 'GET_ALL_SHELTER_PRODUCT_SUCCESS'
export const GET_ALL_SHELTER_PRODUCT_FAIL = 'GET_ALL_SHELTER_PRODUCT_FAIL'
