export const GET_ALL_CITY_REQUEST = 'GET_ALL_CITY_REQUEST'
export const GET_ALL_CITY_SUCCESS = 'GET_ALL_CITY_SUCCESS'
export const GET_ALL_CITY_FAIL = 'GET_ALL_CITY_FAIL'

export const GET_ALL_COUNTRY_REQUEST = 'GET_ALL_COUNTRY_REQUEST'
export const GET_ALL_COUNTRY_SUCCESS = 'GET_ALL_COUNTRY_SUCCESS'
export const GET_ALL_COUNTRY_FAIL = 'GET_ALL_COUNTRY_FAIL'