export const GET_FORM_CATEGORIES_REQUEST = 'GET_FORM_CATEGORIES_REQUEST'
export const GET_FORM_CATEGORIES_SUCCESS = 'GET_FORM_CATEGORIES_SUCCESS'
export const GET_FORM_CATEGORIES_FAIL = 'GET_FORM_CATEGORIES_FAIL'


export const GET_SINGLE_FORM_CATEGORY_REQUEST = 'GET_SINGLE_FORM_CATEGORY_REQUEST'
export const GET_SINGLE_FORM_CATEGORY_SUCCESS = 'GET_SINGLE_FORM_CATEGORY_SUCCESS'
export const GET_SINGLE_FORM_CATEGORY_FAIL = 'GET_SINGLE_FORM_CATEGORY_FAIL'


export const SEND_CLOTHING_FORM_REQUEST = 'SEND_CLOTHING_FORM_REQUEST'
export const SEND_CLOTHING_FORM_SUCCESS = 'SEND_CLOTHING_FORM_SUCCESS'
export const SEND_CLOTHING_FORM_FAIL = 'SEND_CLOTHING_FORM_FAIL'
export const SEND_CLOTHING_FORM_RESET = 'SEND_CLOTHING_FORM_RESET'

export const SEND_MEAL_FORM_REQUEST = 'SEND_MEAL_FORM_REQUEST'
export const SEND_MEAL_FORM_SUCCESS = 'SEND_MEAL_FORM_SUCCESS'
export const SEND_MEAL_FORM_FAIL = 'SEND_MEAL_FORM_FAIL'
export const SEND_MEAL_FORM_RESET = 'SEND_MEAL_FORM_RESET'


export const SEND_SHELTER_FORM_REQUEST = 'SEND_SHELTER_FORM_REQUEST'
export const SEND_SHELTER_FORM_SUCCESS = 'SEND_SHELTER_FORM_SUCCESS'
export const SEND_SHELTER_FORM_FAIL = 'SEND_SHELTER_FORM_FAIL'
export const SEND_SHELTER_FORM_RESET = 'SEND_SHELTER_FORM_RESET'