export const GET_ALL_PERSONTYPE_REQUEST = 'GET_ALL_PERSONTYPE_REQUEST'
export const GET_ALL_PERSONTYPE_SUCCESS = 'GET_ALL_PERSONTYPE_SUCCESS'
export const GET_ALL_PERSONTYPE_FAIL = 'GET_ALL_PERSONTYPE_FAIL'