export const GET_USER_TASKS_REQUEST = 'GET_USER_TASKS_REQUEST'
export const GET_USER_TASKS_SUCCESS = 'GET_USER_TASKS_SUCCESS'
export const GET_USER_TASKS_FAIL = 'GET_USER_TASKS_FAIL'

export const GET_TASKS_BY_CITY_REQUEST = 'GET_TASKS_BY_CITY_REQUEST'
export const GET_TASKS_BY_CITY_SUCCESS = 'GET_TASKS_BY_CITY_SUCCESS'
export const GET_TASKS_BY_CITY_FAIL = 'GET_TASKS_BY_CITY_FAIL'
