export const FILTER_BY_ROLE_REQUEST = 'FILTER_BY_ROLE_REQUEST'
export const FILTER_BY_ROLE_SUCCESS = 'FILTER_BY_ROLE_SUCCESS'
export const FILTER_BY_ROLE_FAIL = 'FILTER_BY_ROLE_FAIL'
export const FILTER_BY_ROLE_RESET = 'FILTER_BY_ROLE_RESET'