export const FILTER_BY_ROLE_REQUEST = 'FILTER_BY_ROLE_REQUEST'
export const FILTER_BY_ROLE_SUCCESS = 'FILTER_BY_ROLE_SUCCESS'
export const FILTER_BY_ROLE_FAIL = 'FILTER_BY_ROLE_FAIL'
export const FILTER_BY_ROLE_RESET = 'FILTER_BY_ROLE_RESET'

export const GET_USER_CLOTHING_BASKET_REQUEST = 'GET_USER_CLOTHING_BASKET_REQUEST'
export const GET_USER_CLOTHING_BASKET_SUCCESS = 'GET_USER_CLOTHING_BASKET_SUCCESS'
export const GET_USER_CLOTHING_BASKET_FAIL = 'GET_USER_CLOTHING_BASKET_FAIL'

export const ADD_CLOTHING_TO_BASKET_REQUEST = 'ADD_CLOTHING_TO_BASKET_REQUEST'
export const ADD_CLOTHING_TO_BASKET_SUCCESS = 'ADD_CLOTHING_TO_BASKET_SUCCESS'
export const ADD_CLOTHING_TO_BASKET_FAIL = 'ADD_CLOTHING_TO_BASKET_FAIL'
export const ADD_CLOTHING_TO_BASKET_RESET = 'ADD_CLOTHING_TO_BASKET_RESET'

export const REMOVE_CLOTHING_FROM_BASKET_REQUEST = 'REMOVE_CLOTHING_FROM_BASKET_REQUEST'
export const REMOVE_CLOTHING_FROM_BASKET_SUCCESS = 'REMOVE_CLOTHING_FROM_BASKET_SUCCESS'
export const REMOVE_CLOTHING_FROM_BASKET_FAIL = 'REMOVE_CLOTHING_FROM_BASKET_FAIL'
export const REMOVE_CLOTHING_FROM_BASKET_RESET = 'REMOVE_CLOTHING_FROM_BASKET_RESET'


export const GET_USER_SHELTER_BASKET_REQUEST = 'GET_USER_SHELTER_BASKET_REQUEST'
export const GET_USER_SHELTER_BASKET_SUCCESS = 'GET_USER_SHELTER_BASKET_SUCCESS'
export const GET_USER_SHELTER_BASKET_FAIL = 'GET_USER_SHELTER_BASKET_FAIL'


export const ADD_SHELTER_TO_BASKET_REQUEST = 'ADD_SHELTER_TO_BASKET_REQUEST'
export const ADD_SHELTER_TO_BASKET_SUCCESS = 'ADD_SHELTER_TO_BASKET_SUCCESS'
export const ADD_SHELTER_TO_BASKET_FAIL = 'ADD_SHELTER_TO_BASKET_FAIL'
export const ADD_SHELTER_TO_BASKET_RESET = 'ADD_SHELTER_TO_BASKET_RESET'

export const REMOVE_SHELTER_FROM_BASKET_REQUEST = 'REMOVE_SHELTER_FROM_BASKET_REQUEST'
export const REMOVE_SHELTER_FROM_BASKET_SUCCESS = 'REMOVE_SHELTER_FROM_BASKET_SUCCESS'
export const REMOVE_SHELTER_FROM_BASKET_FAIL = 'REMOVE_SHELTER_FROM_BASKET_FAIL'
export const REMOVE_SHELTER_FROM_BASKET_RESET = 'REMOVE_SHELTER_FROM_BASKET_RESET'

export const GET_USER_MEAL_BASKET_REQUEST = 'GET_USER_MEAL_BASKET_REQUEST'
export const GET_USER_MEAL_BASKET_SUCCESS = 'GET_USER_MEAL_BASKET_SUCCESS'
export const GET_USER_MEAL_BASKET_FAIL = 'GET_USER_MEAL_BASKET_FAIL'

export const ADD_MEAL_TO_BASKET_REQUEST = 'ADD_MEAL_TO_BASKET_REQUEST'
export const ADD_MEAL_TO_BASKET_SUCCESS = 'ADD_MEAL_TO_BASKET_SUCCESS'
export const ADD_MEAL_TO_BASKET_FAIL = 'ADD_MEAL_TO_BASKET_FAIL'
export const ADD_MEAL_TO_BASKET_RESET = 'ADD_MEAL_TO_BASKET_RESET'

export const REMOVE_MEAL_FROM_BASKET_REQUEST = 'REMOVE_MEAL_FROM_BASKET_REQUEST'
export const REMOVE_MEAL_FROM_BASKET_SUCCESS = 'REMOVE_MEAL_FROM_BASKET_SUCCESS'
export const REMOVE_MEAL_FROM_BASKET_FAIL = 'REMOVE_MEAL_FROM_BASKET_FAIL'
export const REMOVE_MEAL_FROM_BASKET_RESET = 'REMOVE_MEAL_FROM_BASKET_RESET'

export const UPDATE_LIVE_LOCATION_REQUEST = 'UPDATE_LIVE_LOCATION_REQUEST'
export const UPDATE_LIVE_LOCATION_SUCCESS = 'UPDATE_LIVE_LOCATION_SUCCESS'
export const UPDATE_LIVE_LOCATION_FAIL = 'UPDATE_LIVE_LOCATION_FAIL'
export const UPDATE_LIVE_LOCATION_RESET = 'UPDATE_LIVE_LOCATION_RESET'