export const GET_ALL_AREA_REQUEST = 'GET_ALL_AREA_REQUEST'
export const GET_ALL_AREA_SUCCESS = 'GET_ALL_AREA_SUCCESS'
export const GET_ALL_AREA_FAIL = 'GET_ALL_AREA_FAIL'


export const ADD_AREA_REQUEST = 'ADD_AREA_REQUEST'
export const ADD_AREA_SUCCESS = 'ADD_AREA_SUCCESS'
export const ADD_AREA_FAIL = 'ADD_AREA_FAIL'
export const ADD_AREA_RESET = 'ADD_AREA_RESET'

export const DELETE_AREA_REQUEST = 'DELETE_AREA_REQUEST'
export const DELETE_AREA_SUCCESS = 'DELETE_AREA_SUCCESS'
export const DELETE_AREA_FAIL = 'DELETE_AREA_FAIL'
export const DELETE_AREA_RESET = 'DELETE_AREA_RESET'

export const UPDATE_AREA_REQUEST = 'UPDATE_AREA_REQUEST'
export const UPDATE_AREA_SUCCESS = 'UPDATE_AREA_SUCCESS'
export const UPDATE_AREA_FAIL = 'UPDATE_AREA_FAIL'
export const UPDATE_AREA_RESET = 'UPDATE_AREA_RESET'


export const ADD_REQUIRED_PRODUCT_TO_AREA_REQUEST = 'ADD_REQUIRED_PRODUCT_TO_AREA_REQUEST'
export const ADD_REQUIRED_PRODUCT_TO_AREA_SUCCESS = 'ADD_REQUIRED_PRODUCT_TO_AREA_SUCCESS'
export const ADD_REQUIRED_PRODUCT_TO_AREA_FAIL = 'ADD_REQUIRED_PRODUCT_TO_AREA_FAIL'
export const ADD_REQUIRED_PRODUCT_TO_AREA_RESET = 'ADD_REQUIRED_PRODUCT_TO_AREA_RESET'

export const REMOVE_REQURIRED_PRODUCT_FROM_REQUEST = 'REMOVE_REQURIRED_PRODUCT_FROM_REQUEST'
export const REMOVE_REQURIRED_PRODUCT_FROM_SUCCESS = 'REMOVE_REQURIRED_PRODUCT_FROM_SUCCESS'
export const REMOVE_REQURIRED_PRODUCT_FROM_FAIL = 'REMOVE_REQURIRED_PRODUCT_FROM_FAIL'
export const REMOVE_REQURIRED_PRODUCT_FROM_RESET = 'REMOVE_REQURIRED_PRODUCT_FROM_RESET'


export const GET_REQURIRED_PRODUCTS_REQUEST = 'GET_REQURIRED_PRODUCTS_REQUEST'
export const GET_REQURIRED_PRODUCTS_SUCCESS = 'GET_REQURIRED_PRODUCTS_SUCCESS'
export const GET_REQURIRED_PRODUCTS_FAIL = 'GET_REQURIRED_PRODUCTS_FAIL'

export const ADD_REQURIRED_PERSON_TO_AREA_REQUEST = 'ADD_REQURIRED_PERSON_TO_AREA_REQUEST'
export const ADD_REQURIRED_PERSON_TO_AREA_SUCCESS = 'ADD_REQURIRED_PERSON_TO_AREA_SUCCESS'
export const ADD_REQURIRED_PERSON_TO_AREA_FAIL = 'ADD_REQURIRED_PERSON_TO_AREA_FAIL'
export const ADD_REQURIRED_PERSON_TO_AREA_RESET = 'ADD_REQURIRED_PERSON_TO_AREA_RESET'

export const REMOVE_REQURIRED_PERSON_TO_AREA_REQUEST = 'REMOVE_REQURIRED_PERSON_TO_AREA_REQUEST'
export const REMOVE_REQURIRED_PERSON_TO_AREA_SUCCESS = 'REMOVE_REQURIRED_PERSON_TO_AREA_SUCCESS'
export const REMOVE_REQURIRED_PERSON_TO_AREA_FAIL = 'REMOVE_REQURIRED_PERSON_TO_AREA_FAIL'
export const REMOVE_REQURIRED_PERSON_TO_AREA_RESET = 'REMOVE_REQURIRED_PERSON_TO_AREA_RESET'

export const GET_REQURIRED_PEOPLE_REQUEST = 'GET_REQURIRED_PEOPLE_REQUEST'
export const GET_REQURIRED_PEOPLE_SUCCESS = 'GET_REQURIRED_PEOPLE_SUCCESS'
export const GET_REQURIRED_PEOPLE_FAIL = 'GET_REQURIRED_PEOPLE_FAIL'


export const GET_AREAS_BY_PRODUCT_TITLE_REQUEST = 'GET_AREAS_BY_PRODUCT_TITLE_REQUEST'
export const GET_AREAS_BY_PRODUCT_TITLE_SUCCESS = 'GET_AREAS_BY_PRODUCT_TITLE_SUCCESS'
export const GET_AREAS_BY_PRODUCT_TITLE_FAIL = 'GET_AREAS_BY_PRODUCT_TITLE_FAIL'
export const GET_AREAS_BY_PRODUCT_TITLE_RESET = 'GET_AREAS_BY_PRODUCT_TITLE_RESET'