export const ADD_BRAND_REQUEST = 'ADD_BRAND_REQUEST'
export const ADD_BRAND_SUCCESS = 'ADD_BRAND_SUCCESS'
export const ADD_BRAND_FAIL = 'ADD_BRAND_FAIL'
export const ADD_BRAND_RESET = 'ADD_BRAND_RESET'


export const GET_ALL_BRAND_REQUEST = 'GET_ALL_BRAND_REQUEST'
export const GET_ALL_BRAND_SUCCESS = 'GET_ALL_BRAND_SUCCESS'
export const GET_ALL_BRAND_FAIL = 'GET_ALL_BRAND_FAIL'

export const GET_SINGLE_BRAND_REQUEST = 'GET_SINGLE_BRAND_REQUEST'
export const GET_SINGLE_BRAND_SUCCESS = 'GET_SINGLE_BRAND_SUCCESS'
export const GET_SINGLE_BRAND_FAIL = 'GET_SINGLE_BRAND_FAIL'


export const UPDATE_BRAND_REQUEST = 'UPDATE_BRAND_REQUEST'
export const UPDATE_BRAND_SUCCESS = 'UPDATE_BRAND_SUCCESS'
export const UPDATE_BRAND_FAIL = 'UPDATE_BRAND_FAIL'
export const UPDATE_BRAND_RESET = 'UPDATE_BRAND_RESET'


export const DELETE_BRAND_REQUEST = 'DELETE_BRAND_REQUEST'
export const DELETE_BRAND_SUCCESS = 'DELETE_BRAND_SUCCESS'
export const DELETE_BRAND_FAIL = 'DELETE_BRAND_FAIL'
export const DELETE_BRAND_RESET = 'DELETE_BRAND_RESET'


export const GET_ALL_CLOTHES_BRAND_REQUEST = 'GET_ALL_CLOTHES_BRAND_REQUEST'
export const GET_ALL_CLOTHES_BRAND_SUCCESS = 'GET_ALL_CLOTHES_BRAND_SUCCESS'
export const GET_ALL_CLOTHES_BRAND_FAIL = 'GET_ALL_CLOTHES_BRAND_FAIL'

export const GET_ALL_SHELTER_BRAND_REQUEST = 'GET_ALL_SHELTER_BRAND_REQUEST'
export const GET_ALL_SHELTER_BRAND_SUCCESS = 'GET_ALL_SHELTER_BRAND_SUCCESS'
export const GET_ALL_SHELTER_BRAND_FAIL = 'GET_ALL_SHELTER_BRAND_FAIL'

export const GET_ALL_MEAL_BRAND_REQUEST = 'GET_ALL_MEAL_BRAND_REQUEST'
export const GET_ALL_MEAL_BRAND_SUCCESS = 'GET_ALL_MEAL_BRAND_SUCCESS'
export const GET_ALL_MEAL_BRAND_FAIL = 'GET_ALL_MEAL_BRAND_FAIL'