export const ADD_CLOTHES_REQUEST = 'ADD_CLOTHES_REQUEST'
export const ADD_CLOTHES_SUCCESS = 'ADD_CLOTHES_SUCCESS'
export const ADD_CLOTHES_FAIL = 'ADD_CLOTHES_FAIL'
export const ADD_CLOTHES_RESET = 'ADD_CLOTHES_RESET'