export const GET_ALL_CLOTHING_FORM_REQUEST = 'GET_ALL_CLOTHING_FORM_REQUEST'
export const GET_ALL_CLOTHING_FORM_SUCCESS = 'GET_ALL_CLOTHING_FORM_SUCCESS'
export const GET_ALL_CLOTHING_FORM_FAIL = 'GET_ALL_CLOTHING_FORM_FAIL'
export const GET_ALL_CLOTHING_FORM_RESET = 'GET_ALL_CLOTHING_FORM_RESET'


export const ADD_CLOTHING_FORM_REQUEST = 'ADD_CLOTHING_FORM_REQUEST'
export const ADD_CLOTHING_FORM_SUCCESS = 'ADD_CLOTHING_FORM_SUCCESS'
export const ADD_CLOTHING_FORM_FAIL = 'ADD_CLOTHING_FORM_FAIL'
export const ADD_CLOTHING_FORM_RESET = 'ADD_CLOTHING_FORM_RESET'

export const DELETE_CLOTHING_FORM_REQUEST = 'DELETE_CLOTHING_FORM_REQUEST'
export const DELETE_CLOTHING_FORM_SUCCESS = 'DELETE_CLOTHING_FORM_SUCCESS'
export const DELETE_CLOTHING_FORM_FAIL = 'DELETE_CLOTHING_FORM_FAIL'
export const DELETE_CLOTHING_FORM_RESET = 'DELETE_CLOTHING_FORM_RESET'

export const UPDATE_CLOTHING_FORM_REQUEST = 'UPDATE_CLOTHING_FORM_REQUEST'
export const UPDATE_CLOTHING_FORM_SUCCESS = 'UPDATE_CLOTHING_FORM_SUCCESS'
export const UPDATE_CLOTHING_FORM_FAIL = 'UPDATE_CLOTHING_FORM_FAIL'
export const UPDATE_CLOTHING_FORM_RESET = 'UPDATE_CLOTHING_FORM_RESET'