export const ADD_CLOTHES_REQUEST = 'ADD_CLOTHES_REQUEST'
export const ADD_CLOTHES_SUCCESS = 'ADD_CLOTHES_SUCCESS'
export const ADD_CLOTHES_FAIL = 'ADD_CLOTHES_FAIL'
export const ADD_CLOTHES_RESET = 'ADD_CLOTHES_RESET'


export const DELETE_CLOTHES_REQUEST = 'DELETE_CLOTHES_REQUEST'
export const DELETE_CLOTHES_SUCCESS = 'DELETE_CLOTHES_SUCCESS'
export const DELETE_CLOTHES_FAIL = 'DELETE_CLOTHES_FAIL'
export const DELETE_CLOTHES_RESET = 'DELETE_CLOTHES_RESET'

export const UPDATE_CLOTHES_REQUEST = 'UPDATE_CLOTHES_REQUEST'
export const UPDATE_CLOTHES_SUCCESS = 'UPDATE_CLOTHES_SUCCESS'
export const UPDATE_CLOTHES_FAIL = 'UPDATE_CLOTHES_FAIL'
export const UPDATE_CLOTHES_RESET = 'UPDATE_CLOTHES_RESET'