export const GET_ALL_CLOTHING_FORM_REQUEST = 'GET_ALL_CLOTHING_FORM_REQUEST'
export const GET_ALL_CLOTHING_FORM_SUCCESS = 'GET_ALL_CLOTHING_FORM_SUCCESS'
export const GET_ALL_CLOTHING_FORM_FAIL = 'GET_ALL_CLOTHING_FORM_FAIL'
export const GET_ALL_CLOTHING_FORM_RESET = 'GET_ALL_CLOTHING_FORM_RESET'


export const ADD_CLOTHING_FORM_REQUEST = 'ADD_CLOTHING_FORM_REQUEST'
export const ADD_CLOTHING_FORM_SUCCESS = 'ADD_CLOTHING_FORM_SUCCESS'
export const ADD_CLOTHING_FORM_FAIL = 'ADD_CLOTHING_FORM_FAIL'
export const ADD_CLOTHING_FORM_RESET = 'ADD_CLOTHING_FORM_RESET'