export const GET_FORMS_BY_CATEGORYID_REQUEST = 'GET_FORMS_BY_CATEGORYID_REQUEST'
export const GET_FORMS_BY_CATEGORYID_SUCCESS = 'GET_FORMS_BY_CATEGORYID_SUCCESS'
export const GET_FORMS_BY_CATEGORYID_FAIL = 'GET_FORMS_BY_CATEGORYID_FAIL'

export const SEARCH_FORMS_REQUEST = 'SEARCH_FORMS_REQUEST'
export const SEARCH_FORMS_SUCCESS = 'SEARCH_FORMS_SUCCESS'
export const SEARCH_FORMS_FAIL = 'SEARCH_FORMS_FAIL'
export const SEARCH_FORMS_RESET = 'SEARCH_FORMS_RESET'