export const GET_FORM_CATEGORIES_REQUEST = 'GET_FORM_CATEGORIES_REQUEST'
export const GET_FORM_CATEGORIES_SUCCESS = 'GET_FORM_CATEGORIES_SUCCESS'
export const GET_FORM_CATEGORIES_FAIL = 'GET_FORM_CATEGORIES_FAIL'


export const GET_SINGLE_FORM_CATEGORY_REQUEST = 'GET_SINGLE_FORM_CATEGORY_REQUEST'
export const GET_SINGLE_FORM_CATEGORY_SUCCESS = 'GET_SINGLE_FORM_CATEGORY_SUCCESS'
export const GET_SINGLE_FORM_CATEGORY_FAIL = 'GET_SINGLE_FORM_CATEGORY_FAIL'
