export const GET_FORMS_BY_CATEGORYID_REQUEST = 'GET_FORMS_BY_CATEGORYID_REQUEST'
export const GET_FORMS_BY_CATEGORYID_SUCCESS = 'GET_FORMS_BY_CATEGORYID_SUCCESS'
export const GET_FORMS_BY_CATEGORYID_FAIL = 'GET_FORMS_BY_CATEGORYID_FAIL'

export const GET_APPROVED_FORMS_REQUEST = 'GET_APPROVED_FORMS_REQUEST'
export const GET_APPROVED_FORMS_SUCCESS = 'GET_APPROVED_FORMS_SUCCESS'
export const GET_APPROVED_FORMS_FAIL = 'GET_APPROVED_FORMS_FAIL'

export const SEARCH_FORMS_REQUEST = 'SEARCH_FORMS_REQUEST'
export const SEARCH_FORMS_SUCCESS = 'SEARCH_FORMS_SUCCESS'
export const SEARCH_FORMS_FAIL = 'SEARCH_FORMS_FAIL'
export const SEARCH_FORMS_RESET = 'SEARCH_FORMS_RESET'

export const DELETE_FORM_REQUEST = 'DELETE_FORM_REQUEST'
export const DELETE_FORM_SUCCESS = 'DELETE_FORM_SUCCESS'
export const DELETE_FORM_FAIL = 'DELETE_FORM_FAIL'
export const DELETE_FORM_RESET = 'DELETE_FORM_RESET'

export const UPDATE_FORM_REQUEST = 'UPDATE_FORM_REQUEST'
export const UPDATE_FORM_SUCCESS = 'UPDATE_FORM_SUCCESS'
export const UPDATE_FORM_FAIL = 'UPDATE_FORM_FAIL'
export const UPDATE_FORM_RESET = 'UPDATE_FORM_RESET'

export const APPROVE_FORM_REQUEST = 'APPROVE_FORM_REQUEST'
export const APPROVE_FORM_SUCCESS = 'APPROVE_FORM_SUCCESS'
export const APPROVE_FORM_FAIL = 'APPROVE_FORM_FAIL'
export const APPROVE_FORM_RESET = 'APPROVE_FORM_RESET'