export const SAVE_LOCATION_REQUEST = 'SAVE_LOCATION_REQUEST'
export const SAVE_LOCATION_SUCCESS = 'SAVE_LOCATION_SUCCESS'
export const SAVE_LOCATION_FAIL = 'SAVE_LOCATION_FAIL'
export const SAVE_LOCATION_RESET = 'SAVE_LOCATION_RESET'

export const GET_USERS_LOCATIONS_REQUEST = 'GET_USERS_LOCATIONS_REQUEST'
export const GET_USERS_LOCATIONS_SUCCESS = 'GET_USERS_LOCATIONS_SUCCESS'
export const GET_USERS_LOCATIONS_FAIL = 'GET_USERS_LOCATIONS_FAIL'

export const UPDATE_LIVE_LOCATION_SUCCESS = 'UPDATE_LIVE_LOCATION_SUCCESS'
export const UPDATE_LIVE_LOCATION_FAIL = 'UPDATE_LIVE_LOCATION_FAIL'
export const UPDATE_LIVE_LOCATION_RESET = 'UPDATE_LIVE_LOCATION_RESET'