export const GET_ALL_MEAL_NEED_FORM_REQUEST = 'GET_ALL_MEAL_NEED_FORM_REQUEST'
export const GET_ALL_MEAL_NEED_FORM_SUCCESS = 'GET_ALL_MEAL_NEED_FORM_SUCCESS'
export const GET_ALL_MEAL_NEED_FORM_FAIL = 'GET_ALL_MEAL_NEED_FORM_FAIL'
export const GET_ALL_MEAL_NEED_FORM_RESET = 'GET_ALL_MEAL_NEED_FORM_RESET'


export const CREATE_MEAL_NEED_FORM_REQUEST = 'CREATE_MEAL_NEED_FORM_REQUEST'
export const CREATE_MEAL_NEED_FORM_SUCCESS = 'CREATE_MEAL_NEED_FORM_SUCCESS'
export const CREATE_MEAL_NEED_FORM_FAIL = 'CREATE_MEAL_NEED_FORM_FAIL'
export const CREATE_MEAL_NEED_FORM_RESET = 'CREATE_MEAL_NEED_FORM_RESET'

export const DELETE_MEAL_NEED_FORM_REQUEST = 'DELETE_MEAL_NEED_FORM_REQUEST'
export const DELETE_MEAL_NEED_FORM_SUCCESS = 'DELETE_MEAL_NEED_FORM_SUCCESS'
export const DELETE_MEAL_NEED_FORM_FAIL = 'DELETE_MEAL_NEED_FORM_FAIL'
export const DELETE_MEAL_NEED_FORM_RESET = 'DELETE_MEAL_NEED_FORM_RESET'


export const UPDATE_MEAL_NEED_FORM_REQUEST = 'UPDATE_MEAL_NEED_FORM_REQUEST'
export const UPDATE_MEAL_NEED_FORM_SUCCESS = 'UPDATE_MEAL_NEED_FORM_SUCCESS'
export const UPDATE_MEAL_NEED_FORM_FAIL = 'UPDATE_MEAL_NEED_FORM_FAIL'
export const UPDATE_MEAL_NEED_FORM_RESET = 'UPDATE_MEAL_NEED_FORM_RESET'