export const GET_ALL_MEAL_BY_BRAND_REQUEST = 'GET_ALL_MEAL_BY_BRAND_REQUEST'
export const GET_ALL_MEAL_BY_BRAND_SUCCESS = 'GET_ALL_MEAL_BY_BRAND_SUCCESS'
export const GET_ALL_MEAL_BY_BRAND_FAIL = 'GET_ALL_MEAL_BY_BRAND_FAIL'


export const ADD_MEAL_REQUEST = 'ADD_MEAL_REQUEST'
export const ADD_MEAL_SUCCESS = 'ADD_MEAL_SUCCESS'
export const ADD_MEAL_FAIL = 'ADD_MEAL_FAIL'
export const ADD_MEAL_RESET = 'ADD_MEAL_RESET'


export const DELETE_MEAL_REQUEST = 'DELETE_MEAL_REQUEST'
export const DELETE_MEAL_SUCCESS = 'DELETE_MEAL_SUCCESS'
export const DELETE_MEAL_FAIL = 'DELETE_MEAL_FAIL'
export const DELETE_MEAL_RESET = 'DELETE_MEAL_RESET'

export const UPDATE_MEAL_REQUEST = 'UPDATE_MEAL_REQUEST'
export const UPDATE_MEAL_SUCCESS = 'UPDATE_MEAL_SUCCESS'
export const UPDATE_MEAL_FAIL = 'UPDATE_MEAL_FAIL'
export const UPDATE_MEAL_RESET = 'UPDATE_MEAL_RESET'