export const ADD_PERSONTYPE_REQUEST = 'ADD_PERSONTYPE_REQUEST'
export const ADD_PERSONTYPE_SUCCESS = 'ADD_PERSONTYPE_SUCCESS'
export const ADD_PERSONTYPE_FAIL = 'ADD_PERSONTYPE_FAIL'
export const ADD_PERSONTYPE_RESET = 'ADD_PERSONTYPE_RESET'


export const GET_ALL_PERSONTYPE_REQUEST = 'GET_ALL_PERSONTYPE_REQUEST'
export const GET_ALL_PERSONTYPE_SUCCESS = 'GET_ALL_PERSONTYPE_SUCCESS'
export const GET_ALL_PERSONTYPE_FAIL = 'GET_ALL_PERSONTYPE_FAIL'


export const DELETE_PERSONTYPE_REQUEST = 'DELETE_PERSONTYPE_REQUEST'
export const DELETE_PERSONTYPE_SUCCESS = 'DELETE_PERSONTYPE_SUCCESS'
export const DELETE_PERSONTYPE_FAIL = 'DELETE_PERSONTYPE_FAIL'
export const DELETE_PERSONTYPE_RESET = 'DELETE_PERSONTYPE_RESET'


export const UPDATE_PERSONTYPE_REQUEST = 'UPDATE_PERSONTYPE_REQUEST'
export const UPDATE_PERSONTYPE_SUCCESS = 'UPDATE_PERSONTYPE_SUCCESS'
export const UPDATE_PERSONTYPE_FAIL = 'UPDATE_PERSONTYPE_FAIL'
export const UPDATE_PERSONTYPE_RESET = 'UPDATE_PERSONTYPE_RESET'