export const GET_ALL_SHELTER_BY_BRAND_REQUEST = 'GET_ALL_SHELTER_BY_BRAND_REQUEST'
export const GET_ALL_SHELTER_BY_BRAND_SUCCESS = 'GET_ALL_SHELTER_BY_BRAND_SUCCESS'
export const GET_ALL_SHELTER_BY_BRAND_FAIL = 'GET_ALL_SHELTER_BY_BRAND_FAIL'


export const ADD_SHELTER_REQUEST = 'ADD_SHELTER_REQUEST'
export const ADD_SHELTER_SUCCESS = 'ADD_SHELTER_SUCCESS'
export const ADD_SHELTER_FAIL = 'ADD_SHELTER_FAIL'
export const ADD_SHELTER_RESET = 'ADD_SHELTER_RESET'


export const DELETE_SHELTER_REQUEST = 'DELETE_SHELTER_REQUEST'
export const DELETE_SHELTER_SUCCESS = 'DELETE_SHELTER_SUCCESS'
export const DELETE_SHELTER_FAIL = 'DELETE_SHELTER_FAIL'
export const DELETE_SHELTER_RESET = 'DELETE_SHELTER_RESET'

export const UPDATE_SHELTER_REQUEST = 'UPDATE_SHELTER_REQUEST'
export const UPDATE_SHELTER_SUCCESS = 'UPDATE_SHELTER_SUCCESS'
export const UPDATE_SHELTER_FAIL = 'UPDATE_SHELTER_FAIL'
export const UPDATE_SHELTER_RESET = 'UPDATE_SHELTER_RESET'