export const CREATE_SHELTER_NEED_FORM_REQUEST = 'CREATE_SHELTER_NEED_FORM_REQUEST'
export const CREATE_SHELTER_NEED_FORM_SUCCESS = 'CREATE_SHELTER_NEED_FORM_SUCCESS'
export const CREATE_SHELTER_NEED_FORM_FAIL = 'CREATE_SHELTER_NEED_FORM_FAIL'
export const CREATE_SHELTER_NEED_FORM_RESET = 'CREATE_SHELTER_NEED_FORM_RESET'

export const GET_ALL_SHELTER_FORM_REQUEST = 'GET_ALL_SHELTER_FORM_REQUEST'
export const GET_ALL_SHELTER_FORM_SUCCESS = 'GET_ALL_SHELTER_FORM_SUCCESS'
export const GET_ALL_SHELTER_FORM_FAIL = 'GET_ALL_SHELTER_FORM_FAIL'
export const GET_ALL_SHELTER_FORM_RESET = 'GET_ALL_SHELTER_FORM_RESET'

export const DELETE_SHELTER_FORM_REQUEST = 'DELETE_SHELTER_FORM_REQUEST'
export const DELETE_SHELTER_FORM_SUCCESS = 'DELETE_SHELTER_FORM_SUCCESS'
export const DELETE_SHELTER_FORM_FAIL = 'DELETE_SHELTER_FORM_FAIL'
export const DELETE_SHELTER_FORM_RESET = 'DELETE_SHELTER_FORM_RESET'


export const UPDATE_SHELTER_FORM_REQUEST = 'UPDATE_SHELTER_FORM_REQUEST'
export const UPDATE_SHELTER_FORM_SUCCESS = 'UPDATE_SHELTER_FORM_SUCCESS'
export const UPDATE_SHELTER_FORM_FAIL = 'UPDATE_SHELTER_FORM_FAIL'
export const UPDATE_SHELTER_FORM_RESET = 'UPDATE_SHELTER_FORM_RESET'