export const GET_ALL_SUBCATEGORY_REQUEST = 'GET_ALL_SUBCATEGORY_REQUEST'
export const GET_ALL_SUBCATEGORY_SUCCESS = 'GET_ALL_SUBCATEGORY_SUCCESS'
export const GET_ALL_SUBCATEGORY_FAIL = 'GET_ALL_SUBCATEGORY_FAIL'


export const ADD_SUBCATEGORY_REQUEST = 'ADD_SUBCATEGORY_REQUEST'
export const ADD_SUBCATEGORY_SUCCESS = 'ADD_SUBCATEGORY_SUCCESS'
export const ADD_SUBCATEGORY_FAIL = 'ADD_SUBCATEGORY_FAIL'
export const ADD_SUBCATEGORY_RESET = 'ADD_SUBCATEGORY_RESET'

export const UPDATE_SUBCATEGORY_REQUEST = 'UPDATE_SUBCATEGORY_REQUEST'
export const UPDATE_SUBCATEGORY_SUCCESS = 'UPDATE_SUBCATEGORY_SUCCESS'
export const UPDATE_SUBCATEGORY_FAIL = 'UPDATE_SUBCATEGORY_FAIL'
export const UPDATE_SUBCATEGORY_RESET = 'UPDATE_SUBCATEGORY_RESET'

export const DELETE_SUBCATEGORY_REQUEST = 'DELETE_SUBCATEGORY_REQUEST'
export const DELETE_SUBCATEGORY_SUCCESS = 'DELETE_SUBCATEGORY_SUCCESS'
export const DELETE_SUBCATEGORY_FAIL = 'DELETE_SUBCATEGORY_FAIL'
export const DELETE_SUBCATEGORY_RESET = 'DELETE_SUBCATEGORY_RESET'