export const GET_ALL_TASK_REQUEST = 'GET_ALL_TASK_REQUEST'
export const GET_ALL_TASK_SUCCESS = 'GET_ALL_TASK_SUCCESS'
export const GET_ALL_TASK_FAIL = 'GET_ALL_TASK_FAIL'



export const ADD_TASK_REQUEST = 'ADD_TASK_REQUEST'
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS'
export const ADD_TASK_FAIL = 'ADD_TASK_FAIL'
export const ADD_TASK_RESET = 'ADD_TASK_RESET'


export const UPDATE_TASK_REQUEST = 'UPDATE_TASK_REQUEST'
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS'
export const UPDATE_TASK_FAIL = 'UPDATE_TASK_FAIL'
export const UPDATE_TASK_RESET = 'UPDATE_TASK_RESET'

export const GET_TASKS_BY_CITY_REQUEST = 'GET_TASKS_BY_CITY_REQUEST'
export const GET_TASKS_BY_CITY_SUCCESS = 'GET_TASKS_BY_CITY_SUCCESS'
export const GET_TASKS_BY_CITY_FAIL = 'GET_TASKS_BY_CITY_FAIL'
