export const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL";

export const UPDATE_USER_ROLE_REQUEST = "UPDATE_USER_ROLE_REQUEST";
export const UPDATE_USER_ROLE_SUCCESS = "UPDATE_USER_ROLE_SUCCESS";
export const UPDATE_USER_ROLE_FAIL = "UPDATE_USER_ROLE_FAIL";
export const UPDATE_USER_ROLE_RESET = "UPDATE_USER_ROLE_RESET";

export const SEARCH_USERS_BY_NAME_REQUEST = 'SEARCH_USERS_BY_NAME_REQUEST'
export const SEARCH_USERS_BY_NAME_SUCCESS = 'SEARCH_USERS_BY_NAME_SUCCESS'
export const SEARCH_USERS_BY_NAME_FAIL = 'SEARCH_USERS_BY_NAME_FAIL'
export const SEARCH_USERS_BY_NAME_RESET = 'SEARCH_USERS_BY_NAME_RESET'

export const ADD_TASK_TO_USER_REQUEST = 'ADD_TASK_TO_USER_REQUEST'
export const ADD_TASK_TO_USER_SUCCESS = 'ADD_TASK_TO_USER_SUCCESS'
export const ADD_TASK_TO_USER_FAIL = 'ADD_TASK_TO_USER_FAIL'
export const ADD_TASK_TO_USER_RESET = 'ADD_TASK_TO_USER_RESET'

export const REMOVE_TASK_TO_USER_REQUEST = 'REMOVE_TASK_TO_USER_REQUEST'
export const REMOVE_TASK_TO_USER_SUCCESS = 'REMOVE_TASK_TO_USER_SUCCESS'
export const REMOVE_TASK_TO_USER_FAIL = 'REMOVE_TASK_TO_USER_FAIL'
export const REMOVE_TASK_TO_USER_RESET = 'REMOVE_TASK_TO_USER_RESET'


export const GET_NOT_ADDED_TASK_REQUEST = 'GET_NOT_ADDED_TASK_REQUEST'
export const GET_NOT_ADDED_TASK_SUCCESS = 'GET_NOT_ADDED_TASK_SUCCESS'
export const GET_NOT_ADDED_TASK_FAIL = 'GET_NOT_ADDED_TASK_FAIL'

export const GET_USER_TASKS_REQUEST = 'GET_USER_TASKS_REQUEST'
export const GET_USER_TASKS_SUCCESS = 'GET_USER_TASKS_SUCCESS'
export const GET_USER_TASKS_FAIL = 'GET_USER_TASKS_FAIL'

export const FILTER_BY_ROLE_REQUEST = 'FILTER_BY_ROLE_REQUEST'
export const FILTER_BY_ROLE_SUCCESS = 'FILTER_BY_ROLE_SUCCESS'
export const FILTER_BY_ROLE_FAIL = 'FILTER_BY_ROLE_FAIL'
export const FILTER_BY_ROLE_RESET = 'FILTER_BY_ROLE_RESET'