export const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL";

export const UPDATE_USER_ROLE_REQUEST = "UPDATE_USER_ROLE_REQUEST";
export const UPDATE_USER_ROLE_SUCCESS = "UPDATE_USER_ROLE_SUCCESS";
export const UPDATE_USER_ROLE_FAIL = "UPDATE_USER_ROLE_FAIL";
export const UPDATE_USER_ROLE_RESET = "UPDATE_USER_ROLE_RESET";

export const SEARCH_USERS_BY_NAME_REQUEST = 'SEARCH_USERS_BY_NAME_REQUEST'
export const SEARCH_USERS_BY_NAME_SUCCESS = 'SEARCH_USERS_BY_NAME_SUCCESS'
export const SEARCH_USERS_BY_NAME_FAIL = 'SEARCH_USERS_BY_NAME_FAIL'
export const SEARCH_USERS_BY_NAME_RESET = 'SEARCH_USERS_BY_NAME_RESET'